name: Your Workflow Name

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to?'
        required: true
        default: 'stage'

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set DEPLOY_ENV
      id: set-deploy-env
      run: |
        if [ -n "${{ github.event.inputs.environment }}" ]; then
          echo "DEPLOY_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
        fi
        if [ -z "${{ github.event.inputs.environment }}" ]; then
          echo "DEPLOY_ENV=$(echo $GITHUB_REF | sed 's|refs/heads/||')" >> $GITHUB_ENV
        fi

    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python main.py
